[common]
default_envs = yolo_uno

[env:yolo_uno]
platform = espressif32
board = yolo_uno
framework = arduino
build_unflags = -Os
build_flags =
    -O1
    -Ilib
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    https://github.com/knolleary/pubsubclient
    https://github.com/bblanchon/ArduinoJson

lib_ldf_mode = deep
board_build.filesystem = spiffs
board_build.partitions = config/partitions/yolo_uno_8MB.csv
